apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-console-prod
  namespace: v-console-prod
  labels:
    app: v-console-prod
spec:
  selector:
    matchLabels:
      app: v-console-prod
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: v-console-prod
    spec:
      containers:
      - name: v-console-prod
        image: vincentbuiwork/v-console:prod
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.5
            memory: 500M
          limits:
            cpu: 2
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
