apiVersion: v1
kind: Service
metadata:
  name: ng-battleship-prod-service
  labels:
    app: ng-battleship-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.107
  externalIPs:
  - 192.168.1.107
  ports:
  - name: http
    port: 80 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: ng-battleship-prod #find all pod with app name
  sessionAffinity: None
