apiVersion: v1
kind: Service
metadata:
  name: ng-battleship-stage-service
  labels:
    app: ng-battleship-stage
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.107
  externalIPs:
  - 10.24.24.107
  ports:
  - name: http
    port: 82 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: ng-battleship-stage #find all pod with app name
  sessionAffinity: None
