apiVersion: v1
kind: Service
metadata:
  name: v-service-dev-service
  labels:
    app: v-service-dev
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.107
  externalIPs:
  - 10.24.24.107
  ports:
  - name: http
    port: 83 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: v-service-dev #find all pod with app name
  sessionAffinity: None
